### ISSUE TITLE
Error handler barfs if there's no default error document

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#135]
## Expected Behavior

If there is no `error.html` it should show the default Flask error handler page.

## Current Behavior

An uncaught exception leads to an ISE:

```
ERROR:flask.app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask_caching/__init__.py", line 366, in decorated_function
    rv = f(*args, **kwargs)
  File "<string>", line 2, in render_category
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/pony/orm/core.py", line 467, in new_func
    result = func(*args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 243, in render_category
    raise http_error.NotFound("No such view")
werkzeug.exceptions.NotFound: 404 Not Found: No such view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 180, in render_exception
    'args': error.args
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 161, in render_error
    return flask.abort(error_code)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 180, in render_exception
    'args': error.args
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 161, in render_error
    return flask.abort(error_code)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
ERROR:flask.app:Exception on /asldkjfalsj [GET]
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask_caching/__init__.py", line 366, in decorated_function
    rv = f(*args, **kwargs)
  File "<string>", line 2, in render_category
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/pony/orm/core.py", line 467, in new_func
    result = func(*args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 243, in render_category
    raise http_error.NotFound("No such view")
werkzeug.exceptions.NotFound: 404 Not Found: No such view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 180, in render_exception
    'args': error.args
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 161, in render_error
    return flask.abort(error_code)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 180, in render_exception
    'args': error.args
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 161, in render_error
    return flask.abort(error_code)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
ERROR:flask.app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask_caching/__init__.py", line 366, in decorated_function
    rv = f(*args, **kwargs)
  File "<string>", line 2, in render_category
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/pony/orm/core.py", line 467, in new_func
    result = func(*args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 243, in render_category
    raise http_error.NotFound("No such view")
werkzeug.exceptions.NotFound: 404 Not Found: No such view

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 180, in render_exception
    'args': error.args
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 161, in render_error
    return flask.abort(error_code)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 180, in render_exception
    'args': error.args
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/publ/rendering.py", line 161, in render_error
    return flask.abort(error_code)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 707, in abort
    return _aborter(status, *args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/publ.beesbuzz.biz-t6uZXXeD/lib/python3.7/site-packages/werkzeug/exceptions.py", line 687, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
```

**Comment by fluffy-critter** [comment]
So the thing is that `flask.abort()` works by raising an exception, and we're overriding the default exception handler. The real trick is to figure out what the default Flask exception handler is instead. This is not documented though, so it's possibly something that's not intended to be used externally.

It might be better to simply embed a response template.
