### ISSUE TITLE
sqlite3: fix occasional OperationalError when rendering during site index

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#160]
```
Traceback (most recent call last):
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<string>", line 2, in render_category
    """ Rendering functions """
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\orm\core.py", line 467, in new_func
    result = func(*args, **kwargs)
  File "c:\users\fluffy\projects\publ\publ\rendering.py", line 230, in render_category
    if not orm.select(e for e in model.Entry if e.category == category or
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\orm\core.py", line 5661, in __len__
    return len(query._actual_fetch())
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\orm\core.py", line 5502, in _actual_fetch
    cursor = database._exec_sql(sql, arguments)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\orm\core.py", line 863, in _exec_sql
    connection = cache.reconnect(e)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\orm\core.py", line 1686, in reconnect
    if not provider.should_reconnect(exc): reraise(*sys.exc_info())
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\utils\utils.py", line 95, in reraise
    try: raise exc.with_traceback(tb)
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\orm\core.py", line 861, in _exec_sql
    try: new_id = provider.execute(cursor, sql, arguments, returning_id)
  File "<string>", line 2, in execute
    from pony.py23compat import PY2, basestring, unicode, buffer, int_types, iteritems
  File "C:\Users\fluffy\.virtualenvs\Publ-site-9q3QltxW\lib\site-packages\pony\orm\dbapiprovider.py", line 61, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.dbapiprovider.OperationalError: database is locked
```

OperationalErrors like this should just go through a retry of the transaction.

**Comment by fluffy-critter** [comment]
This seems to have been fixed by the various indexing improvements
