### ISSUE TITLE
img_style/div_style test now failing

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#195]
## Expected Behavior

Test entry http://localhost:5000/images/516-Image-attributes should work

## Current Behavior

```
From cffi callback <function cb_image at 0x10b861488>:
Traceback (most recent call last):
  File "/Users/jshagam/.local/share/virtualenvs/Publ-jIbESq8L/lib/python3.7/site-packages/misaka/callbacks.py", line 276, in cb_image
    result = renderer.image(link, title, alt)
  File "/Users/jshagam/projects/Publ/publ/markdown.py", line 76, in image
    alt)
  File "/Users/jshagam/projects/Publ/publ/markdown.py", line 164, in _render_image
    return img.get_img_tag(title, alt_text, **composite_args)
  File "/Users/jshagam/projects/Publ/publ/image/image.py", line 80, in get_img_tag
    **self.get_img_attrs(style, **kwargs)
TypeError: get_img_attrs() got multiple values for argument 'style'
From cffi callback <function cb_image at 0x10b861488>:
Traceback (most recent call last):
  File "/Users/jshagam/.local/share/virtualenvs/Publ-jIbESq8L/lib/python3.7/site-packages/misaka/callbacks.py", line 276, in cb_image
    result = renderer.image(link, title, alt)
  File "/Users/jshagam/projects/Publ/publ/markdown.py", line 76, in image
    alt)
  File "/Users/jshagam/projects/Publ/publ/markdown.py", line 164, in _render_image
    return img.get_img_tag(title, alt_text, **composite_args)
  File "/Users/jshagam/projects/Publ/publ/image/image.py", line 80, in get_img_tag
    **self.get_img_attrs(style, **kwargs)
TypeError: get_img_attrs() got multiple values for argument 'style'
```

Possibly a regression due to the prefix_ additions

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by fluffy-critter** [comment]
Fixed in #196
