### ISSUE TITLE
Spaces in cache keys cause failure to memoize in memcached

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#255]
## Expected Behavior

Cache keys should be normalized to work with memcached.

## Current Behavior

```
ERROR:ThreadPoolExecutor-0_3:flask_caching:Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/__init__.py", line 771, in decorated_function
    f, *args, **kwargs
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/__init__.py", line 565, in make_cache_key
    f, args=args, timeout=_timeout, forced_update=forced_update
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/__init__.py", line 548, in _memoize_version
    dict(zip(fetch_keys, version_data_list)), timeout=timeout
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/backends/memcache.py", line 129, in set_many
    failed_keys = self._client.set_multi(new_mapping, timeout)
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/memcache.py", line 896, in set_multi
    six.iterkeys(mapping), key_prefix)
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/memcache.py", line 821, in _map_and_prefix_keys
    self.check_key(bytes_orig_key, key_extra_len=key_extra_len)
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/memcache.py", line 1320, in check_key
    "Control/space characters not allowed (key=%r)" % key)
memcache.Client.MemcachedKeyCharacterError: Control/space characters not allowed (key=b"beesbuzz.bizpubl.user.User.groups.(<class 'publ.user.User'>, 'https://queer.party/@fluffy')_memver")
ERROR:ThreadPoolExecutor-0_3:flask_caching:Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/__init__.py", line 771, in decorated_function
    f, *args, **kwargs
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/__init__.py", line 565, in make_cache_key
    f, args=args, timeout=_timeout, forced_update=forced_update
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/__init__.py", line 548, in _memoize_version
    dict(zip(fetch_keys, version_data_list)), timeout=timeout
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/flask_caching/backends/memcache.py", line 129, in set_many
    failed_keys = self._client.set_multi(new_mapping, timeout)
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/memcache.py", line 896, in set_multi
    six.iterkeys(mapping), key_prefix)
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/memcache.py", line 821, in _map_and_prefix_keys
    self.check_key(bytes_orig_key, key_extra_len=key_extra_len)
  File "/home/fluffy/.local/share/virtualenvs/beesbuzz.biz-RK9-tIok/lib/python3.7/site-packages/memcache.py", line 1320, in check_key
    "Control/space characters not allowed (key=%r)" % key)
memcache.Client.MemcachedKeyCharacterError: Control/space characters not allowed (key=b"beesbuzz.bizpubl.user.User.groups.(<class 'publ.user.User'>, 'https://queer.party/@fluffy')_memver")
ERROR:ThreadPoolExecutor-0_3:flask_caching:Exception possibly due to cache backend.
```

Trying to memoize based on the current `caching.memoizable` mechanism causes errors like these, especially with users. No idea why this isn't causing errors for other memoizables though -- everything *should* be causing this problem, not just `User`...

## Possible Solution

Have `caching.Memoizable` normalize the cache key better.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by fluffy-critter** [comment]
The puzzling thing here is that in all code paths that handle this stuff, the key should already be getting converted to a hash...
