### ISSUE TITLE
Automatic alt-tag generation fails on external images

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#288]
## Expected Behavior

`![](https://example.com/foo.gif)` should work

## Current Behavior

It fails with an error:

```
AttributeError: 'function' object has no attribute 'decode'
From cffi callback <function cb_image at 0x1023a6b90>:
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/Publ-FUB3ZG92/lib/python3.7/site-packages/misaka/callbacks.py", line 276, in cb_image
    result = renderer.image(link, title, alt)
  File "/Users/fluffy/projects/Publ/publ/markdown.py", line 67, in image
    alt)
  File "/Users/fluffy/projects/Publ/publ/markdown.py", line 155, in _render_image
    return img.get_img_tag(title, alt_text, **composite_args, _mark_rewritten=True)
  File "/Users/fluffy/projects/Publ/publ/image/image.py", line 91, in get_img_tag
    attrs['alt'] = self._filename
  File "/Users/fluffy/projects/Publ/publ/image/external.py", line 81, in _filename
    return os.path.basename(urllib.parse.urlparse(self._get_url).path)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 367, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'function' object has no attribute 'decode'
```

## Possible Solution

Give the `Image` base class a `default_alt_tag` abstractproperty and use that instead

**Comment by fluffy-critter** [comment]
oh wait that's what `_filename` is already... shoot.
