### ISSUE TITLE
Exception information AttributeError: 'NoneType' object has no attribute 'fingerprint'

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#346]
## Current Behavior

Sometimes when items are being indexed, an exception occurs:

```
Traceback (most recent call last):
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "<string>", line 2, in render_category
    """ Rendering functions """
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/pony/orm/core.py", line 528, in new_func
    result = func(*args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/rendering.py", line 251, in render_category
    return render_category_path(category, template)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/rendering.py", line 290, in render_category_path
    view=view_obj)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/rendering.py", line 119, in render_publ_template
    **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask_caching/__init__.py", line 791, in decorated_function
    return f(*args, **kwargs)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/rendering.py", line 111, in do_render
    text = template.render(**args)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/template.py", line 53, in render
    return flask.render_template(self.filename, **args)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/fluffy/Documents/biz.beesbuzz.biz/templates/index.html", line 36, in top-level template code
    {% for entry in view(entry_type_not='sidebar').entries %}
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/utils.py", line 80, in __iter__
    return self._default().__iter__()
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/utils.py", line 53, in _default
    return self._cached_default(flask.request.url, user.get_active())
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/utils.py", line 49, in _cached_default
    return self._func()
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/view.py", line 138, in _entries
    result.append(Entry(record))
  File "/Users/fluffy/.local/share/virtualenvs/biz.beesbuzz.biz-mgLWmDbt/lib/python3.7/site-packages/publ/entry.py", line 49, in __init__
    LOGGER.debug('loaded entry %d, fingerprint=%s', record.id, self._fingerprint.fingerprint)
AttributeError: 'NoneType' object has no attribute 'fingerprint'
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by fluffy-critter** [comment]
This is still happening :(

**Comment by fluffy-critter** [comment]
Reopen was possibly erroneous?
