### ISSUE TITLE
Emoji-only tags fail

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#444]
## Expected Behavior

Tagging an entry with e.g. `Tag: 💜` should work

## Current Behavior

```
ERROR:publ.index:Got error parsing content/blog/chatter/20210703 bookmark-of https_www_jayeless_net_wiki_small-web_html.md
Traceback (most recent call last):
  File "/Users/fluffy/Library/Caches/pypoetry/virtualenvs/beesbuzz.biz-7I0fvtWX-py3.8/lib/python3.8/site-packages/publ/index.py", line 139, in do_scan
    return entry.scan_file(fullpath, relpath, fixup_pass)
  File "<string>", line 2, in scan_file
  File "/Users/fluffy/Library/Caches/pypoetry/virtualenvs/beesbuzz.biz-7I0fvtWX-py3.8/lib/python3.8/site-packages/pony/orm/core.py", line 533, in new_func
    result = func(*args, **kwargs)
  File "/Users/fluffy/Library/Caches/pypoetry/virtualenvs/beesbuzz.biz-7I0fvtWX-py3.8/lib/python3.8/site-packages/publ/entry.py", line 895, in scan_file
    tag_record = model.EntryTag.get(key=key)
  File "/Users/fluffy/Library/Caches/pypoetry/virtualenvs/beesbuzz.biz-7I0fvtWX-py3.8/lib/python3.8/site-packages/pony/orm/core.py", line 4014, in get
    try: return entity._find_one_(kwargs)  # can throw MultipleObjectsFoundError
  File "/Users/fluffy/Library/Caches/pypoetry/virtualenvs/beesbuzz.biz-7I0fvtWX-py3.8/lib/python3.8/site-packages/pony/orm/core.py", line 4112, in _find_one_
    avdict[attr] = attr.validate(val, None, entity, from_db=False)
  File "/Users/fluffy/Library/Caches/pypoetry/virtualenvs/beesbuzz.biz-7I0fvtWX-py3.8/lib/python3.8/site-packages/pony/orm/core.py", line 2547, in validate
    throw(ValueError, 'Attribute %s is required' % (
  File "/Users/fluffy/Library/Caches/pypoetry/virtualenvs/beesbuzz.biz-7I0fvtWX-py3.8/lib/python3.8/site-packages/pony/utils/utils.py", line 106, in throw
    raise exc
ValueError: Attribute EntryTag.key is required
```

Presumably the key normalizer ends up just stripping the emoji out. There is probably some configuration in awesome-slugify that can help.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by fluffy-critter** [comment]
The non-ASCII translations are handled by [Unidecode](https://github.com/avian2/unidecode) which doesn't appear to support emoji-names, and adding it in a friendly way would be difficult.

IMaybe before slugifying, a tag name should be passed through [emoji.demojize](https://pypi.org/project/emoji/)
